name: Publish Containers to GitHub Container Registry

on:
  push:
    branches: ["main"]
    tags: ["*"]
    paths:
      - 'api/**'
      - 'controller/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            runner: ubuntu-24.04-arm64
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata for api
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api
          tags: |
            type=ref,event=branch,suffix=-${{ matrix.platform }}
            type=ref,event=tag,suffix=-${{ matrix.platform }}
            type=raw,value=main-${{ matrix.platform }},enable={{is_default_branch}}

      - name: Extract Docker metadata for controller
        id: meta-controller
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-controller
          tags: |
            type=ref,event=branch,suffix=-${{ matrix.platform }}
            type=ref,event=tag,suffix=-${{ matrix.platform }}
            type=raw,value=main-${{ matrix.platform }},enable={{is_default_branch}}

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image for api
        id: build-and-push-api
        uses: docker/build-push-action@v5
        with:
          context: ./api
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image for controller
        id: build-and-push-controller
        uses: docker/build-push-action@v5
        with:
          context: ./controller
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta-controller.outputs.tags }}
          labels: ${{ steps.meta-controller.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Create multi-platform manifests
  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-platform manifest for api
        run: |
          # Extract tag without platform suffix
          TAG=$(echo "${{ github.ref_name }}" | sed 's/refs\/heads\///g' | sed 's/refs\/tags\///g')
          if [ "$TAG" = "main" ]; then
            TAG="main"
          fi
          
          docker buildx imagetools create -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api:$TAG \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api:$TAG-linux/amd64 \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api:$TAG-linux/arm64

      - name: Create and push multi-platform manifest for controller
        run: |
          # Extract tag without platform suffix
          TAG=$(echo "${{ github.ref_name }}" | sed 's/refs\/heads\///g' | sed 's/refs\/tags\///g')
          if [ "$TAG" = "main" ]; then
            TAG="main"
          fi
          
          docker buildx imagetools create -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-controller:$TAG \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-controller:$TAG-linux/amd64 \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-controller:$TAG-linux/arm64
