name: Pip Audit

on:
  push:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-latest
    container:
      image: python:3.11

    steps:
      - uses: actions/checkout@v4

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Audit Python Dependencies in api
        run: |
          cd api
          pip-audit
      
      - name: Audit Python Dependencies in controller
        run: |
          cd controller
          pip-audit
