name: Pip Audit

on:
  push:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - uses: actions/checkout@v4

      - name: Install pip-audit
        run: |
          pip install pip-audit

      - name: Prepare and audit Python dependencies in api
        run: |
          cd api
          pip install poetry
          poetry install --no-interaction --no-ansi
          pip-audit

      - name: Prepare and audit Python dependencies in controller
        run: |
          cd controller
          pip install poetry
          poetry install --no-interaction --no-ansi
          pip-audit
