name: Run Pytest

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.11

    defaults:
      run:
        working-directory: api/
        
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run pytest
        run: poetry run pytest -m "not active_runtime"
